import { config } from '../config';
import { encodeBufferToBase64 } from '../utils/base64';
import { OpenRouterResponse } from '../types';
import fs from 'fs';
import path from 'path';

const STICKER_PROMPT = `Based on the provided image, generate a 5×5 grid (25 items) of Telegram-ready stickers.
Each sticker must feature the same person, with recognizable facial features, proportions, and identity, but without caricature distortion.
Use a clean vector-style cute aesthetic, similar to modern Telegram sticker packs.
Stickers must have a transparent background.

Style Requirements:
- Cute, polished vector animation style.
- No exaggerated or distorted facial features.
- Keep the person's identity clearly recognizable across all 25 stickers.
- Smooth outlines, soft shading, expressive poses.
- Colors should remain consistent with the original appearance.

Content Requirements:
Generate 25 different emotions and micro-situations, one per sticker, including but not limited to:
happy, excited, surprised, thinking, angry (soft/cute), sad, crying, laughing, facepalm, embarrassed, sleepy, proud, confused, mischievous, shocked, worried, determined, thumbs up, thumbs down, waving, wink, neutral, "OK" gesture, "heart sign", celebration pose

Output Requirements:
- 25 separate sticker images arranged in a 5×5 grid.
- Transparent PNGs.
- Uniform framing and proportions so the set looks cohesive.
- Maintain character consistency across all stickers.`;

export class StickerGeneratorService {
    async generateStickerGrid(imageBuffer: Buffer): Promise<string> {
        try {
            const base64Image = encodeBufferToBase64(imageBuffer, 'image/jpeg');

            console.log('Calling OpenRouter API...');

            const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${config.openRouterApiKey}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    model: config.modelName,
                    messages: [
                        {
                            role: 'user',
                            content: [
                                {
                                    type: 'text',
                                    text: STICKER_PROMPT,
                                },
                                {
                                    type: 'image_url',
                                    image_url: {
                                        url: base64Image,
                                    },
                                },
                            ],
                        },
                    ],
                    modalities: ['image', 'text'],
                    image_config: {
                        aspect_ratio: '1:1',
                    },
                }),
            });

            if (!response.ok) {
                const errorText = await response.text();
                throw new Error(`OpenRouter API error: ${response.statusText} - ${errorText}`);
            }

            const result = (await response.json()) as unknown as OpenRouterResponse;

            if (!result.choices || result.choices.length === 0) {
                throw new Error('No response from AI model');
            }

            const message = result.choices[0].message;

            if (!message.images || message.images.length === 0) {
                throw new Error('No images generated by AI model');
            }

            // Get the first generated image (should be the 5x5 grid)
            const imageUrl = message.images[0].image_url.url;

            console.log('Image generated successfully');

            // Download and save the image
            const imagePath = await this.saveGeneratedImage(imageUrl);

            return imagePath;
        } catch (error) {
            console.error('Error generating sticker grid:', error);
            throw error;
        }
    }

    private async saveGeneratedImage(dataUrl: string): Promise<string> {
        // Extract base64 data from data URL
        const matches = dataUrl.match(/^data:image\/(\w+);base64,(.+)$/);

        if (!matches) {
            throw new Error('Invalid image data URL');
        }

        const extension = matches[1];
        const base64Data = matches[2];
        const buffer = Buffer.from(base64Data, 'base64');

        // Save to temp directory
        const tempDir = path.join(process.cwd(), 'temp');
        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir, { recursive: true });
        }

        const filename = `grid_${Date.now()}.${extension}`;
        const filepath = path.join(tempDir, filename);

        await fs.promises.writeFile(filepath, buffer);

        return filepath;
    }
}

export const stickerGeneratorService = new StickerGeneratorService();
